#%RAML 1.0
title: HMRC Trust Registration Service
version: Beta 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/
documentation:
  - title: Trust Registration Service
    content: An API for registering and updating trusts.
mediaType: application/hal+json
resourceTypes:
  base: !include resourceTypes/base.raml
types:
  Trustees: !include schemas/trust.json#/properties/trustees
  Beneficiaries: !include schemas/trust.json#/properties/beneficiaries
  Settlors: !include schemas/trust.json#/properties/settlor
  Protectors: !include schemas/trust.json#/properties/protector
/trusts:
  type: base
  get:
    description: Retrieves all the trusts available to the user
  post:
    description: Submits an entire set of data for a trust
  /utr:
    /{trn}:
        type: base
        uriParameters:
          trn:
            type: string
            displayName: The TRN of the trust.
        get:
          description: Retrieves the UTR of the trust
  /{utr}:
    type: base
    uriParameters:
      utr:
        type: string
        displayName: The SA UTR of the trust.
    get:
      description: Retrieves a specific trust
    /lead-trustee-individual:
      type: base
      get:
        description: Retrieves the information for an lead Trustee as an individual
      put:
        description: Updates the information for an lead Trustee as an individual
    /lead-trustee-company:
      type: base
      get:
        description: Retrieves the information for an lead Trustee as an company
      put:
        description: Updates the information for an lead Trustee as an company
    /trustees:
      type: base
      get:
        description: Retrieves all the trustees of the Trust
        responses:
          200:
            body:
              application/json:
                type: Trustees
                example: !include examples/trustees.json
      put:
        description: Updates all the trustees of the Trust
        body:
          application/json:
              type: Trustees
              example: !include examples/trustees.json
    /beneficiaries:
      type: base
      get:
        description: Retrieves all the beneficiaries of the Trust
        responses:
          200:
            body:
              application/json:
                type: Beneficiaries
                example: !include examples/beneficiaries.json
      put:
        description: Updates all the beneficiaries of the Trust
        body:
          application/json:
              type: Beneficiaries
              example: !include examples/beneficiaries.json
    /settlors:
      type: base
      get:
        description: Retrieves all the settlors for the Trust
        responses:
          200:
            body:
              application/json:
                type: Settlors
                example: !include examples/settlors.json
      put:
        description: Updates all the settlors for the Trust
        body:
          application/json:
              type: Settlors
              example: !include examples/settlors.json
    /natural-persons:
      type: base
      get:
        description: Retrieves all the "natural persons" for the Trust
      put:
        description: Updates all the "natural persons" for the Trust
    /protectors:
      type: base
      get:
        description: Retrieves all the protectors for the Trust
        responses:
          200:
            body:
              application/json:
                type: Protectors
                example: !include examples/protectors.json
      put:
        description: Updates all the protectors for the Trust
        body:
          application/json:
            type: Protectors
            example: !include examples/protectors.json
    /confirmation:
      type: base
      post:
        description: Confirms no change to the trust
    /delete:
      type: base
      delete:
        description: Deletes the Trust
  /lead-trustee-individual:
    type: base
    post:
      description: Registers a lead Trustee as an individual
  /lead-trustee-company:
    type: base
    post:
      description: Registers a lead Trustee as an company
