headers:
  Content-Type:
    description: The content type of the request
    type: string
    required: false
    enum: [ application/vnd.hmrc.1.0+json ]
post?:
  responses:
    200:
      description: Success
    400:
      description: |
        The request was invalid or cannot be otherwise served. An accompanying
        error message will explain further.
    401:
      description: Authentication credentials were missing or incorrect.
    403:
      description: |
        The request has been refused. An error message will explain further. It
        is likely the current user does not have permission to update the data
        for the trust.
    404:
      description: |
        The URI requested is invalid or the resource (i.e. trust) requested
        does not exist.
    500:
      description: |
        Something is broken. Try again later. If the problem persists contact
        support.
    503:
      description: |
        The API is unavailable. Try again later.
get?:
  responses:
    200:
      description: Success
    400:
      description: |
        The request was invalid or cannot be otherwise served. An accompanying
        error message will explain further.
    401:
      description: Authentication credentials were missing or incorrect.
    403:
      description: |
        The request has been refused. An error message will explain further. It
        is likely the current user does not have permission to update the data
        for the trust.
    404:
      description: |
        The URI requested is invalid or the resource (i.e. trust) requested
        does not exist.
    500:
      description: |
        Something is broken. Try again later. If the problem persists contact
        support.
    503:
      description: |
        The API is unavailable. Try again later.
put?:
  responses:
    200:
      description: Success
    400:
      description: |
        The request was invalid or cannot be otherwise served. An accompanying
        error message will explain further.
    401:
      description: Authentication credentials were missing or incorrect.
    403:
      description: |
        The request has been refused. An error message will explain further. It
        is likely the current user does not have permission to update the data
        for the trust.
    404:
      description: |
        The URI requested is invalid or the resource (i.e. trust) requested
        does not exist.
    500:
      description: |
        Something is broken. Try again later. If the problem persists contact
        support.
    503:
      description: |
        The API is unavailable. Try again later.
delete?:
  responses:
    200:
      description: Success
    400:
      description: |
        The request was invalid or cannot be otherwise served. An accompanying
        error message will explain further.
    401:
      description: Authentication credentials were missing or incorrect.
    403:
      description: |
        The request has been refused. An error message will explain further. It
        is likely the current user does not have permission to update the data
        for the trust.
    404:
      description: |
        The URI requested is invalid or the resource (i.e. trust) requested
        does not exist.
    500:
      description: |
        Something is broken. Try again later. If the problem persists contact
        support.
    503:
      description: |
        The API is unavailable. Try again later.
