#%RAML 1.0

title: Trust Registration Service
description: An API for registering and updating trusts.
version: 1.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include https://developer.service.hmrc.gov.uk/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/securitySchemes.raml
  headers: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/headers.raml
  annotations: https://developer.service.hmrc.gov.uk/api-documentation/assets/common/modules/annotations.raml

  base: !include resourceTypes/base.raml
  
  Trust: !include schemas/trust.json#/definitions/trust
  Estate: !include schemas/estate.json#/definitions/estate

/trusts:

  post:
    displayName: Full Trust Registration
    description: Submits an entire set of data for a trust
    is:
      - headers.acceptHeader
    (annotations.scope): "write:trusts-and-estates"
    securedBy: [ sec.oauth_2_0: { scopes: [ "write:trusts-and-estates" ] } ]
    responses:
      200:
        body:
          application/json:
            type: !include "schemas/trn.json"
            example: !include "examples/trn.json"
    body:
      application/json:
        type: !include "schemas/trust.json"
        example: !include examples/trust.json


/estates:
  post:
    displayName: Register Estate
    description: Submits an entire set of data for a estate
    is:
      - headers.acceptHeader
    (annotations.scope): "write:trusts-and-estates"
    securedBy: [ sec.oauth_2_0: { scopes: [ "write:trusts-and-estates" ] } ]
    responses:
      200:
        body:
          application/json:
            type: !include "schemas/trn.json"
            example: !include "examples/trn.json"
    body:
      application/json:
        type: !include "schemas/estate.json"
        example: !include examples/estate.json
