#%RAML 1.0

title: Trust Registration Service
description: An API for registering and updating trusts.
version: 2.0
protocols: [ HTTPS ]
baseUri: https://api.service.hmrc.gov.uk/

documentation:
 - title: Overview
   content: !include docs/overview.md
 - title: Versioning
   content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/versioning.md
 - title: Errors
   content: !include http://api-documentation-raml-frontend.service/api-documentation/assets/common/docs/errors.md

mediaType: [ application/json, application/hal+json ]

uses:
  sec: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/securitySchemes.raml
  headers: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/headers.raml
  annotations: http://api-documentation-raml-frontend.service/api-documentation/assets/common/modules/annotations.raml

/trusts:
  get:
    displayName: Get all trusts
    description: Retrieves all the trusts available to the user
    is:
      - headers.acceptHeader

    (annotations.scope): "read:trusts-and-estates"
    securedBy: [ sec.oauth_2_0: { scopes: [ "read:trusts-and-estates" ] } ]
    responses:
      200:
        body:
          application/json:
            type: !include "schemas/trust.json"
            example: !include "examples/trust.json"
  post:
    displayName: Full Trust Registration
    description: Submits an entire set of data for a trust
    is:
      - headers.acceptHeader
    (annotations.scope): "write:trusts-and-estates"
    securedBy: [ sec.oauth_2_0: { scopes: [ "write:trusts-and-estates" ] } ]
    responses:
      200:
        body:
          application/json:
            type: !include "schemas/trn.json"
            example: !include "examples/trn.json"
    body:
      application/json:
        type: !include "schemas/trust.json"
        example: !include examples/trust.json
  /{utr}:
    uriParameters:
      utr:
        description: The 10 digit self-assessment UTR for the individual.
        type: string
        example: "2234567890"
    get:
      displayName: Get Trust
      description: Retrieves a specific trust
      is:
        - headers.acceptHeader
      (annotations.scope): "read:trusts-and-estates"
      securedBy: [ sec.oauth_2_0: { scopes: [ "read:trusts-and-estates" ] } ]
      responses:
        200:
          body:
            application/json:
              type: !include "schemas/trust.json"
              example: !include "examples/trust.json"

    /close:
      put:
        displayName: Close trust
        description: Closes the specified trust
        is:
          - headers.acceptHeader
        (annotations.scope): "write:trusts-and-estates"
        securedBy: [ sec.oauth_2_0: { scopes: [ "write:trusts-and-estates" ] } ]
        responses:
          200:
            body:
              application/json:
                type: !include "schemas/trn.json"
                example: !include "examples/trn.json"

    /lead-trustee-individual:
      get:
        displayName: Get lead trustee individual
        description: Retrieves the information for an lead trustee as an individual
        is:
          - headers.acceptHeader
        (annotations.scope): "read:trusts-and-estates"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:trusts-and-estates" ] } ]
        responses:
          200:
            body:
              application/json:
                type: !include "schemas/lead-trustee-individual.json"
                example: !include "examples/lead-trustee-individual.json"
      put:
        displayName: Update Lead Trustee Individual
        description: Updates the information for an lead Trustee as an individual
        is:
          - headers.acceptHeader
        (annotations.scope): "read:trusts-and-estates"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:trusts-and-estates" ] } ]
        body:
          application/json:
            type: !include "schemas/lead-trustee-individual.json"
            example: !include "examples/lead-trustee-individual.json"
    /lead-trustee-company:
      get:
        displayName: Get lead trustee company
        description: Retrieves the information for an lead trustee as a company
        is:
          - headers.acceptHeader
        (annotations.scope): "read:trusts-and-estates"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:trusts-and-estates" ] } ]
        responses:
          200:
            body:
              application/json:
                type: !include "schemas/lead-trustee-company.json"
                example: !include "examples/lead-trustee-company.json"
      put:
        displayName: Update Lead Trustee Company
        description: Updates the information for an lead Trustee as a company
        is:
          - headers.acceptHeader
        (annotations.scope): "read:trusts-and-estates"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:trusts-and-estates" ] } ]
        body:
          application/json:
            type: !include "schemas/lead-trustee-company.json"
            example: !include "examples/lead-trustee-company.json"
    /trustees:
      get:
        displayName: Get Trustees
        description: Retrieves all the trustees of the Trust
        is:
          - headers.acceptHeader
        (annotations.scope): "read:trusts-and-estates"
        securedBy: [ sec.oauth_2_0: { scopes: [ "read:trusts-and-estates" ] } ]
        responses:
          200:
            body:
              application/json:
                type: !include "schemas/trustees.json"
                example: !include "examples/trustees.json"
#      put:
#        displayName: Update Trustees
#        description: Updates all the trustees of the Trust
#        is:
#          - headers.acceptHeader
#        (annotations.scope): "read:trusts-and-estates"
#        securedBy: [ sec.oauth_2_0: { scopes: [ "read:trusts-and-estates" ] } ]
#        body:
#          application/json:
#            type: !include "schemas/trustees.json"
#            example: !include "examples/trustees.json"
#    /beneficiaries:
#      type: base
#      get:
#        displayName: Get Beneficiaries
#        description: Retrieves all the beneficiaries of the Trust
#        responses:
#          200:
#            body:
#              application/json:
#                type: Beneficiaries
#                #example: !include examples/beneficiaries.json
#      put:
#        displayName: Update Beneficiaries
#        description: Updates all the beneficiaries of the Trust
#        body:
#          application/json:
#              type: Beneficiaries
#              #example: !include examples/beneficiaries.json
#    /settlors:
#      type: base
#      get:
#        displayName: Get Settlors
#        description: Retrieves all the settlors for the Trust
#        responses:
#          200:
#            body:
#              application/json:
#                type: Settlors
#                #example: !include examples/settlors.json
#      put:
#        displayName: Update Beneficiaries
#        description: Updates all the settlors for the Trust
#        body:
#          application/json:
#              type: Settlors
#              #example: !include examples/settlors.json
#    /natural-persons:
#      type: base
#      get:
#        displayName: Get Natural Persons
#        description: Retrieves all the "natural persons" for the Trust
#        responses:
#          200:
#            body:
#              application/json:
#                type: NaturalPersons
#                #example: !include examples/natural-people.json
#      put:
#        displayName: Update Natural Persons
#        description: Updates all the "natural persons" for the Trust
#        body:
#          application/json:
#              type: NaturalPersons
#              #example: !include examples/natural-people.json
#    /protectors:
#      type: base
#      get:
#        displayName: Get Protectors
#        description: Retrieves all the protectors for the Trust
#        responses:
#          200:
#            body:
#              application/json:
#                type: Protectors
#                #example: !include examples/protectors.json
#      put:
#        displayName: Update Protectors
#        description: Updates all the protectors for the Trust
#        body:
#          application/json:
#            type: Protectors
#            #example: !include examples/protectors.json
#    /no-change:
#      type: base
#      put:
#        displayName: No Change
#        description: Confirms no change to the trust
#        responses:
#          200:
#            body:
#              application/json:
#                type: NoChange
#                #example: !include examples/no-change.json
#  /lead-trustee-individual:
#    type: base
#    post:
#      displayName: Register Lead Trustee Individual
#      description: Registers a lead Trustee as an individual
#      body:
#        application/json:
#          type: LeadTrusteeIndividual
#          #example: !include examples/lead-trustee-individual.json
#  /lead-trustee-company:
#    type: base
#    post:
#      displayName: Register Lead Trustee Company
#      description: Registers a lead Trustee as an company
#      body:
#        application/json:
#          type: LeadTrusteeCompany
#          #example: !include examples/lead-trustee-company.json
#/estates:
#  type: base
#  get:
#    displayName: My Estates
#    description: Retrieves all the estates available to the user
#    responses:
#      200:
#        body:
#          application/json:
#            type: Estate
#            #example: !include examples/estate.json
#  post:
#    displayName: Register Estate
#    description: Submits an entire set of data for a estate
#  /{identifier}:
#    type: base
#    uriParameters:
#      utr:
#        type: string
#        displayName: The SA UTR of the estate.
#    get:
#      displayName: Get Estate
#      description: Retrieve a specific estate
#      responses:
#        200:
#          body:
#            application/json:
#              type: Estate
#              #example: !include examples/estate.json
#    delete:
#      displayName: Delete Estate
#      description: Deletes a specific estate
